// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzmmEwAmkrEFSoy_-T9IsJ-Oyzxtpwc4s',
    appId: '1:654546656277:web:e570a1c05b577c06d1c21c',
    messagingSenderId: '654546656277',
    projectId: 'sigacidades',
    authDomain: 'sigacidades.firebaseapp.com',
    storageBucket: 'sigacidades.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuYcJdFFt6b0FIJDKQ71hG3iTc1q76SPE',
    appId: '1:654546656277:android:ddf723bae3d20a39d1c21c',
    messagingSenderId: '654546656277',
    projectId: 'sigacidades',
    storageBucket: 'sigacidades.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnLJlf1qRmlQbynxn4-jc952VI_u3Jyys',
    appId: '1:654546656277:ios:622431c9bb1aab09d1c21c',
    messagingSenderId: '654546656277',
    projectId: 'sigacidades',
    storageBucket: 'sigacidades.appspot.com',
    iosBundleId: 'com.example.sigacidades',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnLJlf1qRmlQbynxn4-jc952VI_u3Jyys',
    appId: '1:654546656277:ios:622431c9bb1aab09d1c21c',
    messagingSenderId: '654546656277',
    projectId: 'sigacidades',
    storageBucket: 'sigacidades.appspot.com',
    iosBundleId: 'com.example.sigacidades',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzmmEwAmkrEFSoy_-T9IsJ-Oyzxtpwc4s',
    appId: '1:654546656277:web:9ddc31be85003239d1c21c',
    messagingSenderId: '654546656277',
    projectId: 'sigacidades',
    authDomain: 'sigacidades.firebaseapp.com',
    storageBucket: 'sigacidades.appspot.com',
  );
}
